name: Publish Docker image

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: populate docker meta
        id: docker-meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: |
            ghcr.io/amphineko/hatd/hath
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=sha,format=long

      - name: setup qemu
        uses: docker/setup-qemu-action@v3.0.0

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: "./hath/"
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
